import os
import sys

THIS_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT_DIR = os.path.abspath(os.path.join(THIS_DIR, ".."))
IN_FILE = os.path.join(PROJECT_DIR, "default-auto-pickup-items.txt")
OUT_FILE = os.path.join(PROJECT_DIR, "DefaultAutoPickupItems.cs")

f = open(IN_FILE, "r")
data = f.read()
f.close()
enabled = []
for line in data.split("\n"):
    line = line.strip()
    if (not line or line[0] == '#'):
        continue
    enabled.append(line)
f = open(OUT_FILE, "w")
f.write(\
"""
// This file was auto-generated by the %(script)s script in the pre-build step of the super_dave project.

public static class DefaultAutoPickupItems {
    public static string[] enabled_items = new string[] {
%(items)s
    };
}
""" % {
    'script': os.path.basename(__file__),
    'items': ",\n".join(['        "%s"' % item for item in enabled]),
})
f.close()
